title: Mike McQuaid
description: Staff Engineer and Homebrew Project Leader

author:
  name: Mike McQuaid
  email: mike@mikemcquaid.com
  uri: https://mikemcquaid.com
  twitter: MikeMcQuaid

twitter:
  username: MikeMcQuaid

logo: /images/header.jpg

permalink: pretty

exclude:
  - bin
  - CNAME
  - Gemfile*
  - Guardfile
  - Rakefile,
  - ReadMe.md
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links

feed:
  path: atom.xml

sass:
  style: :compressed

defaults:
  - scope:
      type: posts
    values:
      layout: article
  - scope:
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
    values:
      image: /images/header.jpg

collections:
  talks:
    output: true
    permalink: /talks/:title/

github:
  repository_nwo: MikeMcQuaid/mikemcquaid.github.io
