title: Mike McQuaid
url: mikemcquaid.com
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]
# Same as GitHub Pages
# https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
safe: true
lsi: false
pygments: true
exclude: [bin, vendor]
