title: Mike McQuaid
description: Raise.dev CTO and Homebrew Project Leader

author:
  name: Mike McQuaid
  email: mike@mikemcquaid.com
  uri: https://mikemcquaid.com
  twitter: MikeMcQuaid

twitter:
  username: MikeMcQuaid
  card: summary

logo: /images/default-card.png

social:
  name: Mike McQuaid
  links:
    - https://github.com/MikeMcQuaid
    - https://mastodon.mikemcquaid.com/@mike
    - https://www.linkedin.com/in/mkmcqd
    - https://twitter.com/MikeMcQuaid

permalink: "/:title/"

exclude:
  - bin
  - CNAME
  - Gemfile*
  - LICENSE.txt
  - Rakefile,
  - ReadMe.md
  - vendor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-asciidoc

feed:
  path: atom.xml
  posts_limit: 25
  collections:
    - talks

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
    values:
      image: /images/default-card.png

collections:
  talks:
    output: true
    permalink: "/:collection/:title/"

github:
  repository_nwo: MikeMcQuaid/mikemcquaid.com
