name: Mike McQuaid
description: The home page for a software engineer named Mike McQuaid.
author:
  name: Mike McQuaid
  email: mike@mikemcquaid.com
  uri: http://mikemcquaid.com
  twitter: mikemcquaid
url: http://mikemcquaid.com
permalink: pretty

blog:
  name: A Liberal Christian Liberal
  description: Mike McQuaid's musings on life blog.

# Same as GitHub Pages
# https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
# Disable despite enabled on GitHub Pages for supported plugins to work.
# safe: true
kramdown:
  input: GFM
  hard_wrap: false
lsi: false
highlighter: rouge

exclude: [bin, vendor, CNAME, Gemfile, Gemfile.lock, Guardfile, Rakefile,
          ReadMe.md, style.scss]
gems:
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: atom.xml

sass:
  sass_dir: _sass
  style: :compressed
defaults:
  - scope:
      type: "posts"
    values:
      layout: "article"
  - scope:
      type: "blog_posts"
    values:
      layout: "blog_post"
  - scope:
      path: "blog"
      type: "pages"
    values:
      layout: "blog_page"
collections:
  blog_posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
