title: Mike McQuaid
url: http://mikemcquaid.com
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [smart]
# Same as GitHub Pages
# https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
# Disable despite enabled on GitHub Pages for supported plugins to work.
# safe: true
lsi: false
pygments: true
exclude: [bin, vendor, CNAME, Gemfile, Gemfile.lock, Guardfile, Rakefile,
          ReadMe.md, style.scss]
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
